"""create service_tickets table

Revision ID: 58d62f36c3d0
Revises:
Create Date: 2026-03-10 04:39:08.328107
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "58d62f36c3d0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("HARDWARE", "SOFTWARE", "NETWORK", "SECURITY", "OTHER", name="service_category").create(op.get_bind())
    sa.Enum("HIGH", "MEDIUM", "LOW", name="service_urgency").create(op.get_bind())
    op.create_table(
        "service_tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "urgency",
            postgresql.ENUM("HIGH", "MEDIUM", "LOW", name="service_urgency", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "category",
            postgresql.ENUM(
                "HARDWARE",
                "SOFTWARE",
                "NETWORK",
                "SECURITY",
                "OTHER",
                name="service_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("first_occurrence", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_error_message",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("error_message_details", sa.Text(), nullable=True),
        sa.Column("assignee", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_tickets")
    sa.Enum("HIGH", "MEDIUM", "LOW", name="service_urgency").drop(op.get_bind())
    sa.Enum("HARDWARE", "SOFTWARE", "NETWORK", "SECURITY", "OTHER", name="service_category").drop(op.get_bind())
    # ### end Alembic commands ###
